services:
  # A web service on the Ruby native runtime
  - type: web
    runtime: node
    name: sinatra-app
    repo: https://github.com/Bartimeus482/SeverlessRender # Default: Repo containing render.yaml
    region: frankfurt # Default: oregon
    plan: free    # Default: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bp-dp
          property: connectionString

databases:
  - name: bp-dp
    region: frankfurt
    plan: free
